In [3]:
!pip install tensorflow_text

In [4]:
import tensorflow_hub as hub
import tensorflow_text as text

In [5]:
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"
preprocessing_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"

In [7]:
testing_text = ['it is a nice movie','i did not like this movie']
bert_preprocess_model = hub.KerasLayer(preprocessing_url)
preprocessed_text= bert_preprocess_model(testing_text)
preprocessed_text

{'input_type_ids': <tf.Tensor: shape=(2, 128), dtype=int32, numpy=
 array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>,
 'input_word_ids': <tf.Tensor: shape=(2, 128), dtype

In [9]:
bert_model = hub.KerasLayer(encoder_url)
bert_results=bert_model(preprocessed_text)

In [10]:
bert_results.keys()

dict_keys(['encoder_outputs', 'pooled_output', 'sequence_output', 'default'])

In [13]:
bert_results['encoder_outputs']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.16410059,  0.00558281, -0.06615587, ...,  0.13247788,
          0.06047495,  0.04807232],
        [-0.26989847, -0.44966713,  0.26438606, ...,  0.8828676 ,
          0.68998426, -0.02690683],
        [-0.9687057 , -0.48246843, -0.02973063, ...,  0.45747268,
          0.34720218,  0.47530624],
        ...,
        [-0.08237743, -0.23343818,  0.6328615 , ...,  0.5380231 ,
         -0.11457731,  0.08047457],
        [-0.1869021 , -0.24476217,  0.5127703 , ...,  0.57309437,
         -0.00139688, -0.01559808],
        [-0.06248425, -0.19513944,  0.53815305, ...,  0.8616757 ,
         -0.28411034, -0.07366083]],

       [[ 0.0990182 ,  0.00929476, -0.09582523, ...,  0.08805759,
          0.1342361 ,  0.02080018],
        [ 0.68833804,  0.79528755, -0.8073422 , ...,  0.49915168,
          1.2681987 , -0.05405985],
        [ 0.92719513, -0.53096825,  0.4035824 , ..., -0.6426655 ,
          0.20699832, -0.5409811 ],
        ...,